Repository LibrePCB/librepcb-parts-generator, pull requests merged in 2023-08, with the labels that each got.

#103 Generate output into corresponding library directory
  dfn_configs.py
  generate_capacitor_radial_tht.py
  generate_chip.py
  generate_connectors.py
  generate_dfn.py
  generate_dip.py
  generate_idc.py
  generate_led.py
  generate_mosfet_dual.py
  generate_qfp.py
  generate_so.py
  generate_stm_mcu.py
Labels: enhancement

#104 qfp: Fix duplicate sentence in description
  generate_qfp.py
Labels: bug

#105 Automatically escape strings by StringValue entity
  common.py
  entities/common.py
  generate_capacitor_radial_tht.py
  generate_connectors.py
  generate_led.py
  generate_stm_mcu.py
  test_common.py
  test_entities.py
Labels: enhancement

#100 Add Diode Outline packages
  generate_do.py
  uuid_cache_do.csv
Labels: ready for review

#110 idc: Enhance packages with LibrePCB 0.1 features
  entities/device.py
  generate_idc.py
  test_entities.py
  uuid_cache_idc.csv
Labels: enhancement
